# This file is machine-generated - editing it directly is not advised

julia_version = "1.14.0-DEV"
manifest_format = "2.1"
project_hash = "f149aa5eb0e664c7f5e1c841bde169db33d0f1d7"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
version = "1.11.0"

    [deps.Base64.syntax]
    julia_version = "1.14.0-DEV"

[[deps.CodeTracking]]
deps = ["InteractiveUtils", "REPL", "UUIDs"]
git-tree-sha1 = "cfb7a2e89e245a9d5016b70323db412b3a7438d5"
registries = "General"
uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
version = "3.0.2"

    [deps.CodeTracking.syntax]
    julia_version = "1.10.0"

[[deps.DataAPI]]
git-tree-sha1 = "abe83f3a2f1b857aac70ef8b269080af17764bbe"
registries = "General"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.16.0"

    [deps.DataAPI.syntax]
    julia_version = "1.0.0"

[[deps.DataValueInterfaces]]
git-tree-sha1 = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
registries = "General"
uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464"
version = "1.0.0"

    [deps.DataValueInterfaces.syntax]
    julia_version = "1.0.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"
version = "1.11.0"

    [deps.Dates.syntax]
    julia_version = "1.14.0-DEV"

[[deps.FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
version = "1.11.0"

    [deps.FileWatching.syntax]
    julia_version = "1.14.0-DEV"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
version = "1.11.0"

    [deps.InteractiveUtils.syntax]
    julia_version = "1.14.0-DEV"

[[deps.IteratorInterfaceExtensions]]
git-tree-sha1 = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
registries = "General"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "1.0.0"

    [deps.IteratorInterfaceExtensions.syntax]
    julia_version = "1.0.0"

[[deps.JuliaSyntaxHighlighting]]
deps = ["StyledStrings"]
uuid = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"
version = "1.13.0"

    [deps.JuliaSyntaxHighlighting.syntax]
    julia_version = "1.12.0"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"
version = "1.11.0"

    [deps.Logging.syntax]
    julia_version = "1.14.0-DEV"

[[deps.Markdown]]
deps = ["Base64", "JuliaSyntaxHighlighting", "StyledStrings"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
version = "1.11.0"

    [deps.Markdown.syntax]
    julia_version = "1.14.0-DEV"

[[deps.MyterialColors]]
git-tree-sha1 = "01d8466fb449436348999d7c6ad740f8f853a579"
registries = "General"
uuid = "1c23619d-4212-4747-83aa-717207fae70f"
version = "0.3.0"

    [deps.MyterialColors.syntax]
    julia_version = "1.6.0"

[[deps.OrderedCollections]]
git-tree-sha1 = "f9b03759e9ef463718934fbed30820b39997511e"
registries = "General"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "2.0.2"

    [deps.OrderedCollections.syntax]
    julia_version = "1.7.1"

[[deps.Parameters]]
deps = ["OrderedCollections", "UnPack"]
git-tree-sha1 = "0ed04c372da78ff5b98e35e3bd4f4ca9931299cc"
registries = "General"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.13.1"

    [deps.Parameters.syntax]
    julia_version = "1.5.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"
version = "1.11.0"

    [deps.Printf.syntax]
    julia_version = "1.14.0-DEV"

[[deps.ProgressLogging]]
deps = ["Logging", "SHA", "UUIDs"]
git-tree-sha1 = "f0803bc1171e455a04124affa9c21bba5ac4db32"
registries = "General"
uuid = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
version = "0.1.6"

    [deps.ProgressLogging.syntax]
    julia_version = "0.7.0"

[[deps.REPL]]
deps = ["Base64", "Dates", "FileWatching", "InteractiveUtils", "JuliaSyntaxHighlighting", "Markdown", "Sockets", "StyledStrings", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
version = "1.11.0"

    [deps.REPL.syntax]
    julia_version = "1.14.0-DEV"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

    [deps.Random.syntax]
    julia_version = "1.14.0-DEV"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "1.13.0"

    [deps.SHA.syntax]
    julia_version = "1.0.0"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"
version = "1.11.0"

    [deps.Sockets.syntax]
    julia_version = "1.14.0-DEV"

[[deps.StyledStrings]]
uuid = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
version = "1.13.0"

    [deps.StyledStrings.syntax]
    julia_version = "1.11.0"

[[deps.TableTraits]]
deps = ["IteratorInterfaceExtensions"]
git-tree-sha1 = "c06b2f539df1c6efa794486abfb6ed2022561a39"
registries = "General"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "1.0.1"

    [deps.TableTraits.syntax]
    julia_version = "0.7.0"

[[deps.Tables]]
deps = ["DataAPI", "DataValueInterfaces", "IteratorInterfaceExtensions", "OrderedCollections", "TableTraits"]
git-tree-sha1 = "a94d9bdda1b7bed0046cea645639ab3f62196fac"
registries = "General"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
version = "1.14.0"

    [deps.Tables.syntax]
    julia_version = "1.9.0"

[[deps.Term]]
deps = ["CodeTracking", "Dates", "InteractiveUtils", "Logging", "Markdown", "MyterialColors", "OrderedCollections", "Parameters", "ProgressLogging", "REPL", "StyledStrings", "Tables", "TermInput", "UUIDs", "Unicode"]
path = "."
uuid = "fc4d45e9-466a-442a-96c6-79f727d2219d"
version = "2.2.0-terminput"

    [deps.Term.syntax]
    julia_version = "1.11.0"

[[deps.TermInput]]
deps = ["InteractiveUtils", "Markdown", "REPL", "StyledStrings"]
path = "../TermInput.jl"
uuid = "e53b28ee-00f8-475a-85b8-1918fdda0ee8"
version = "0.1.0"
weakdeps = ["JuliaSyntaxHighlighting"]

    [deps.TermInput.extensions]
    TermInputHighlightExt = "JuliaSyntaxHighlighting"

    [deps.TermInput.syntax]
    julia_version = "1.10.0"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
version = "1.11.0"

    [deps.UUIDs.syntax]
    julia_version = "1.14.0-DEV"

[[deps.UnPack]]
git-tree-sha1 = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"
registries = "General"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
version = "1.0.2"

    [deps.UnPack.syntax]
    julia_version = "1.0.0"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
version = "1.11.0"

    [deps.Unicode.syntax]
    julia_version = "1.14.0-DEV"

[registries.General]
url = "https://github.com/JuliaRegistries/General.git"
uuid = "23338594-aafe-5451-b93e-139f81909106"
